<a href="https://colab.research.google.com/github/hbechara/HertieML/blob/main/Lesson1Maths.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

You can take a look at the documentation for numpy here:
https://numpy.org/doc/stable/reference

In [ ]:
import numpy as np

In [ ]:
A = np.array([1,2])
B = np.array([[1,2],[3,4]])
C = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

print(A.shape)
print(B.shape)
print(C.shape)

(2,)
(2, 2)
(2, 2, 3)


In [ ]:
print(A)
print(B)
print(C)

[1 2]
[[1 2]
 [3 4]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
# What do you think the shape of this matrix is going to be?

D = np.random.rand(2,3)

print(D)

[[0.71605178 0.9886141  0.21151589]
 [0.90044565 0.37483871 0.3630812 ]]


In [ ]:
# Arrays can be indexed just like lists.

print(D[1,1])

0.374838714042773


In [ ]:
# I can also assign elements like in lists

D[1,1] = 99
print(D)

[[ 0.71605178  0.9886141   0.21151589]
 [ 0.90044565 99.          0.3630812 ]]


In [ ]:
# Let us use NumPy to transpose a matrix

A = np.array([[1, 2, 3], [4, 5, 6]])
print('Original Array:',A)
A_T = A.transpose()
print('Transposed Array:', A_T)

Let's do something easy now. 


* [Add the two matrices below](https://numpy.org/doc/stable/reference/generated/numpy.add.html)





In [ ]:
A = np.array([[1,2],[3,4],[5,6]])
B = np.array([[10,20],[30,40],[1,2]])

In [ ]:
C = np.add(A,B)
print(C.shape)
print(C)

(3, 2)
[[11 22]
 [33 44]
 [ 6  8]]


Multiply the two matrices below

In [ ]:
A = np.array([[1,2],[3,4]])
B = np.array([[10,20],[30,40]])

In [ ]:
C = A.dot(B)
print(C.shape)

Find the inverse of the matrix below

(Hint: use numpy.linalg function)

In [ ]:
A = np.array([[6,2,1],[7,4,2],[1,2,3]])

A_I = np.linalg.inv(A)

print(A_I)

[[ 4.00000000e-01 -2.00000000e-01  3.17206578e-17]
 [-9.50000000e-01  8.50000000e-01 -2.50000000e-01]
 [ 5.00000000e-01 -5.00000000e-01  5.00000000e-01]]


Ok one more. Let's find the transpose of this matrix.

In [ ]:
A = np.array([[1, 2, 3], [4, 5, 6]])

A_T = np.transpose(A)

print(A_T)

[[1 4]
 [2 5]
 [3 6]]


Let's do something a bit harder. 
Let's write a test for np.linalg.inv

inv returns the inverse of a matrix. How can we test that this function is working properly?